#!/usr/bin/env bash

# Create our VPC

VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--tag-specifications 'ResourceType=vpc, Tags=[{Key=Name, Value=my-vpc-3}]' \
--region ca-central-1 \
--query Vpc.VpcId \
--output text)

echo $VPC_ID

# create an IGW

# attach an IGW

# create a new subnet

# explicitly associate subnets

# add a route for our RT to our IGW