#!/usr/bin/env bash

# where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

# lets create output folder
mkdir -p $OUTPUT_DIR

# Generate a random number
# to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES; i++)); do
    # Generate a random filename
    FILENAME="$OUTPUT_DIR/file_$i.txt"

    # Gererate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done